Repository ALGORITHM-STUDY-A/TRENDS_BE, pull requests merged in 2024-11, with the labels that each got.

#15 [test] cd test 1
  .github/workflows/dev_CD.yml
  .github/workflows/dev_CI.yml
  .gitignore
  Dockerfile
  src/main/java/com/example/trend/service/TestController.java
  src/main/resources/application.yml
Labels: :sparkles: feat, :construction_worker: cicd, :test_tube: test

#16 [test] CD test 2
  src/main/java/com/example/trend/web/TestController.java
  src/test/java/com/example/trend/TrendApplicationTests.java
Labels: :sparkles: feat, :construction_worker: cicd, :test_tube: test

#17 [test] CD test 3
  Dockerfile
Labels: :sparkles: feat, :construction_worker: cicd

#18 [test] CD test 3
  src/main/java/com/example/trend/config/SecurityConfig.java
  src/main/java/com/example/trend/web/TestController.java
Labels: :sparkles: feat, :construction_worker: cicd

#19 [test] CD test 4
  src/main/java/com/example/trend/config/SecurityConfig.java
  src/main/java/com/example/trend/web/TestController.java
Labels: :sparkles: feat, :construction_worker: cicd

#20 [test] CD test 5
  src/main/java/com/example/trend/web/TestController.java
Labels: :sparkles: feat, :construction_worker: cicd

#21 [fix] CORS 설정 수정
  src/main/java/com/example/trend/config/SecurityConfig.java
Labels: :sparkles: feat, :construction_worker: cicd

#12 [chore] BaseEntity 상속 연결
  src/main/java/com/example/trend/domain/Bookmark.java
  src/main/java/com/example/trend/domain/Comment.java
  src/main/java/com/example/trend/domain/CommentLikes.java
  src/main/java/com/example/trend/domain/Location.java
  src/main/java/com/example/trend/domain/Plan.java
  src/main/java/com/example/trend/domain/PlanImage.java
  src/main/java/com/example/trend/domain/PlanLikes.java
Labels: :pencil2: chore

#26 [feat] 회원 기능 MVP 기능 구현 완료
  build.gradle
  src/main/java/com/example/trend/api/code/status/ErrorStatus.java
  src/main/java/com/example/trend/api/exception/handler/EmailCategoryHandler.java
  src/main/java/com/example/trend/config/SecurityConfig.java
  src/main/java/com/example/trend/domain/Member.java
  src/main/java/com/example/trend/repository/CompanyRepository.java
  src/main/java/com/example/trend/service/MailService.java
  src/main/java/com/example/trend/service/companyService/CompanyService.java
  src/main/java/com/example/trend/service/companyService/CompanyServiceImpl.java
  src/main/java/com/example/trend/service/memberService/MemberServiceImpl.java
  src/main/java/com/example/trend/web/MailController.java
  src/main/java/com/example/trend/web/a/dto/companyDTO/CompanyProfileFindDTO.java
  src/main/java/com/example/trend/web/a/dto/memberDTO/MemberJoinDTO.java
  src/main/java/com/example/trend/web/companyController/CompanyController.java
  src/main/resources/application.yml
Labels: :sparkles: feat
